[tool.poetry]
name = "web"
version = "0.1.0"
description = ""
authors = ["Palermo <kantser.artur@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
